site_name: John's Certificates
site_url: https://grokify.github.io/grokify-certificates
docs_dir: src
theme: readthedocs
markdown_extensions:
    - attr_list
nav:
- 'Home': index.md
- 'Topics':
    - 'Machine Learning (1)': 'machine-learning.md'
    - 'Product (1)': 'product.md'
    - 'Programming (8)': 'programming.md'
    - 'Scrum (9)': 'scrum.md'
